name: kafka-service

include:
  - ${KAFKA_SERVER_ABSOLUTE_PATH}/docker-compose.yml
  - ${KAFKA_CONTROL_ABSOLUTE_PATH}/docker-compose.yml
  - ${KAFKA_PRODUCER_BANK_ABSOLUTE_PATH}/docker-compose.yml
  - ${KAFKA_CONSUMER_ACCOUNTANT_ABSOLUTE_PATH}/docker-compose.yml
  - ${KAFKA_CONSUMER_NOTIFICATION_ABSOLUTE_PATH}/docker-compose.yml

services:
  placeholder:
    image: alpine
    command: "true" # Lệnh này chạy xong thoát luôn, trả về code 0 (thành công)
    profiles: ["debug"] # Thêm dòng này để nó KHÔNG tự chạy khi bạn gõ 'up' thông thường


