---
spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 10
      properties:
        enable.dempotence: true
        delivery.timeout.ms: 120000
    properties:
      # Thoi gian cho truoc khi thu lai khi gap lai metadata (mac dinh 100ms)
      retry.backoff.ms: 10000
      # Thoi gian toi da de làm moi metadata (mac dinh 5 phut)
      metadata.max.age.ms: 300000

#logging.level.org.pache.kafka.clients.NetworkClient=ERROR

---
# Cấu hình cho profile DEV
spring:
  config:
    activate:
      on-profile: dev

---
# Cấu hình cho profile loc
spring:
  config:
    activate:
      on-profile: loc

---
# Cấu hình cho profile PRD
spring:
  config:
    activate:
      on-profile: prd

