services:
  base-config:
    volumes:
      - ${SPRING_SWAGGER_ABSOLUTE_PATH}/application.properties:/app/${SPRING_SWAGGER_JAR_PATH}/application.properties
      - ${SPRING_WEB_ABSOLUTE_PATH}/application.properties:/app/${SPRING_WEB_JAR_PATH}/application.properties
  base-with-data-config:
    extends: base-config
    volumes:
      - ../database/connection/mysql/application.properties:/app/database/connection/mysql/application.properties
      - ../database/config/hikariCP/application.properties:/app/database/config/hikariCP/application.properties