server:
  port: ${project.port:0}
  servlet:
    context-path: /${project.contextPath}

spring:
  application:
    name: ${project.appName:}

---
# Cấu hình cho profile DEV
spring:
  config:
    activate:
      on-profile: dev

test:
  a:
    c: dev5

---
# Cấu hình cho profile loc
spring:
  config:
    activate:
      on-profile: loc

test:
  a:
    c: loc7

---
# Cấu hình cho profile PRD
spring:
  config:
    activate:
      on-profile: prd

test:
  a:
    c: prd9333
